### ISSUE TITLE
Suggestion: program in the README

### ISSUE THREAD

**Issue by Datseris** [crstnbr/JuliaWorkshop19#5]
Hi, thanks for this!

Just a quick suggestion: could be helpful to have a png of the 3-day program to be displayed in the read me, so it is possible to match the folders on the repo with the time you allocated for them.

**Comment by crstnbr** [comment]
Yes, makes sense. I'll put the schedule into the readme as well.

(Note, however, that the schedule really is the "planned schedule". If you are interested in more accurate time estimates for some parts for you own workshop, feel free to write me private message on discourse or slack.)
